import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const localesDir = path.resolve(__dirname, '../locales');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf-8'));

// Modern Standard Arabic dictionary for exam portal
const arMap = {
  // Common
  "common.appName": "بوابة امتحانات المدرسة",
  "common.search": "بحث...",
  "common.refresh": "تحديث",
  "common.save": "حفظ",
  "common.saveChanges": "حفظ التغييرات",
  "common.cancel": "إلغاء",
  "common.delete": "حذف",
  "common.edit": "تعديل",
  "common.create": "إنشاء",
  "common.actions": "إجراءات",
  "common.status": "الحالة",
  "common.active": "نشط",
  "common.inactive": "غير نشط",
  "common.open": "مفتوح",
  "common.closed": "مغلق",
  "common.draft": "مسودة",
  "common.loading": "جاري التحميل...",
  "common.error": "خطأ",
  "common.tryAgain": "حاول مرة أخرى",
  "common.none": "لا يوجد",
  "common.optional": "اختياري",
  "common.confirm": "تأكيد",
  "common.back": "رجوع",
  "common.close": "إغلاق",
  "common.copy": "نسخ",
  "common.copied": "تم النسخ إلى الحافظة",
  "common.all": "الكل",
  "common.yes": "نعم",
  "common.no": "لا",
  "common.language": "اللغة",
  "common.theme": "المظهر",
  "common.aiAssistant": "المساعد الذكي",
  "common.unsavedWarning": "لديك تغييرات غير محفوظة. هل أنت تأكد من الإغلاق؟",
  "common.confirmAction": "تأكيد الإجراء",
  "common.done": "مكتمل",
  "common.minutes_zero": "0 دقيقة",
  "common.minutes_one": "دقيقة واحدة",
  "common.minutes_two": "دقيقتان",
  "common.minutes_few": "{{count}} دقائق",
  "common.minutes_many": "{{count}} دقيقة",
  "common.minutes_other": "{{count}} دقيقة",
  "common.questions_zero": "0 سؤال",
  "common.questions_one": "سؤال واحد",
  "common.questions_two": "سؤالان",
  "common.questions_few": "{{count}} أسئلة",
  "common.questions_many": "{{count}} سؤالاً",
  "common.questions_other": "{{count}} سؤال",
  "common.attempts_zero": "0 محاولة",
  "common.attempts_one": "محاولة واحدة",
  "common.attempts_two": "محاولتان",
  "common.attempts_few": "{{count}} محاولات",
  "common.attempts_many": "{{count}} محاولة",
  "common.attempts_other": "{{count}} محاولة",
  "common.students_zero": "0 طالب",
  "common.students_one": "طالب واحد",
  "common.students_two": "طالبان",
  "common.students_few": "{{count}} طلاب",
  "common.students_many": "{{count}} طالباً",
  "common.students_other": "{{count}} طالب",
  "common.exams_zero": "0 اختبار",
  "common.exams_one": "اختبار واحد",
  "common.exams_two": "اختباران",
  "common.exams_few": "{{count}} اختبارات",
  "common.exams_many": "{{count}} اختباراً",
  "common.exams_other": "{{count}} اختبار",
  "common.connected": "متصل بالسيرفر",
  "common.connectingToServer": "جاري الاتصال بالسيرفر...",
  "common.goHome": "الذهاب للوحة التحكم",
  "common.retry": "إعادة المحاولة",

  // Nav
  "nav.dashboard": "لوحة التحكم",
  "nav.students": "الطلاب",
  "nav.exams": "الاختبارات",
  "nav.categories": "الفئات",
  "nav.results": "النتائج",
  "nav.settings": "الإعدادات",
  "nav.profile": "الملف الشخصي",
  "nav.signOut": "تسجيل الخروج",
  "nav.lightMode": "الوضع الفاتح",
  "nav.darkMode": "الوضع الداكن",
  "nav.systemTheme": "مظهر النظام",

  // AI
  "ai.assistantTitle": "المساعد الذكي",
  "ai.portalTab": "سؤال",
  "ai.formatTab": "تنسيق الأسئلة",
  "ai.greeting": "كيف يمكنني مساعدتك في بوابة الاختبارات؟",
  "ai.askPlaceholder": "اسأل عن البوابة...",
  "ai.disclaimer": "قد يخطئ الذكاء الاصطناعي. يرجى التحقق من التفاصيل.",

  // Exams
  "exams.title": "إدارة الاختبارات",
  "exams.subtitle": "إنشاء وتنظيم وتوزيع اختبارات المدرسة",
  "exams.createNew": "إنشاء اختبار جديد",
  "exams.deleteExam": "حذف الاختبار",
  "exams.deleteConfirmTitle": "تأكيد حذف الاختبار",
  "exams.deletePreserveNotice": "هل أنت تأكد من حذف الاختبار '{{title}}'؟ سيتم حذف تعريف الاختبار وأسئلته ورابطه بشكل دائم، بينما ستظل نتائج ودرجات الطلاب محفوظة بالكامل.",
  "exams.resultsWillBeKept": "تم حفظ {{count}} نتيجة طالب في الأرشيف",
  "exams.resultsKeptSub": "يمكن الاطلاع على جميع المحاولات والدرجات في صفحة النتائج.",
  "exams.typeTitleToConfirm": "اكتب اسم الاختبار لتأكيد الحذف",
  "exams.forceSubmitOptionLabel": "إنهاء وتسليم محاولات الطلاب قيد الإجراء فوراً وحذف الاختبار",

  // Exam taking
  "exam.studentPortal": "بوابة امتحانات الطلاب",
  "exam.enterStudentId": "أدخل رقم الطالب",
  "exam.enterPassword": "أدخل كلمة المرور",
  "exam.startExam": "بدء الاختبار",
  "exam.resumeExam": "استئناف الاختبار",
  "exam.submitExam": "تسليم الاختبار ✓",
  "exam.confirmSubmitTitle": "تأكيد تسليم الاختبار",
  "exam.confirmSubmitMessage": "هل أنت تأكد من تسليم الاختبار؟ لا يمكنك تغيير إجاباتك بعد التسليم.",
  "exam.threeMinWarningTitle": "🚨 تنبيه الوقت: متبقي 3 دقائق!",
  "exam.threeMinWarningBanner": "⚠️ تنبيه: متبقي أقل من 3 دقائق! يرجى مراجعة إجاباتك والاستعداد للتسليم.",
  "exam.gotIt": "فهمت ومتابعة",
  "exam.examDescription": "وصف الاختبار",
  "exam.examInstructions": "المناحي والتعليمات",
  "exam.viewInstructions": "عرض الوصف والتعليمات",

  // Results & Email
  "results.title": "نتائج الاختبارات والدرجات",
  "results.subtitle": "عرض وتصحيح محاولات الطلاب وإرسال الشهادات والنتائج",
  "results.emailResult": "إرسال النتيجة بالبريد",
  "results.emailedStatus": "تم الإرسال بالبريد",
  "results.updatedAfterSending": "تم التحديث بعد الإرسال",
  "results.sendingEmail": "جاري الإرسال...",
  "results.sendUpdatedResult": "إرسال النتيجة المحدثة",
  "results.examDeletedBadge": "تم حذف الاختبار",
  "results.deleteResultsBtn": "حذف النتائج",
  "results.deleteResultsConfirmTitle": "تأكيد حذف جميع النتائج",
  "results.cannotRetakeDeletedTooltip": "تم حذف هذا الاختبار ولا يمكن إعادة محاولته.",
};

console.log('Script initialized for Arabic translation generation');
